# Jekyll Settings
name: Dokka
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
highlighter: pygments
exclude:
  - vendor
  - bin
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - rake
include:
  - doc
  - _init_.md

# Site Settings
baseurl: /dokka
