name: CI

on: pull_request

jobs:
  test-ubuntu:
    strategy:
      matrix:
        version: [ 8, 11, 15, 16 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.version }}
      - run: ./gradlew clean test --stacktrace

  test-windows:
    strategy:
      matrix:
        version: [ 11, 15, 16 ]
      fail-fast: false
    runs-on: windows-latest
    env:
      GRADLE_OPTS: -Xms3G -Xmx5G
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.version }}
      - run: ./gradlew clean test --stacktrace --no-daemon --parallel --max-workers=1
