name: S3-snapshots

on: push

env:
  branch-name: ${GITHUB_REF#refs/heads/}
  bucket-name: 'dokka-snapshots'

jobs:
  coroutines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dokka
        uses: actions/checkout@v2
        with:
          path: dokka

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Publish dokka locally
        run: ./gradlew clean publishToMavenLocal --stacktrace
        working-directory: ./dokka

      - name: Checkout coroutines
        uses: actions/checkout@v2
        with:
          repository: 'kamildoleglo/kotlinx.coroutines'
          ref: 'aws'
          path: coroutines

      - name: Document coroutines
        run: ./gradlew clean :dokkaCollector --stacktrace
        working-directory: ./coroutines

      - name: Configure AWS credentials for S3 access
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Copy files to dokka's S3 bucket
        run: |
          aws s3 --recursive rm s3://${{ env.bucket-name }}/${{ env.branch-name }}/coroutines/prev
          aws s3 --recursive mv s3://${{ env.bucket-name }}/${{ env.branch-name }}/coroutines/latest s3://${{ env.bucket-name }}/${{ env.branch-name }}/coroutines/prev
          aws s3 sync ./coroutines/build/dokkaCollector s3://${{ env.bucket-name }}/${{ env.branch-name }}/coroutines/latest
